name: Deploy Website Code to GitHub Pages

# Trigger the workflow on push to the Prod branch.
on:
  push:
    branches:
      - Prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Step 2: Copy 'Website code' folder from Prod to gh-pages
      - name: Copy Website code folder
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          
          # Clone gh-pages branch
          git clone --branch=gh-pages https://github.com/blake-noske/blake-noske.github.io.git gh-pages
          
          # Copy the content from 'Website code' folder to the cloned branch
          cp -r Website\ code/* gh-pages/
          
          # Go to the gh-pages directory
          cd gh-pages

          # Add, commit and push the changes
          git add .
          git commit -m "Update website"
          git push origin gh-pages
