name: Deploy Website Code to GitHub Pages

on:
  push:
    branches:
      - Prod  # Only triggers when changes are pushed to the Prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Prod branch
        uses: actions/checkout@v2
        with:
          ref: Prod  # Checkout the Prod branch

      - name: Copy Website Code folder to gh-pages branch
        run: |
          git config --global blake-noske
          git config --global blake.noske@gmail.com
          # Switch to the gh-pages branch
          git checkout gh-pages || git checkout --orphan gh-pages
          # Remove all files (if any) from gh-pages branch
          git rm -rf .
          # Copy the contents of Website code folder
          cp -r Website\ code/* .
          # Add and commit changes
          git add .
          git commit -m "Update website from Website code folder"
          git push origin gh-pages --force
